-- record.saleType
-- record.source
-- record.language
-- record.originalPropertyCategory
-- record.propertyCategory
-- record.sellerType
-- record.price
-- record.netPrice
-- record.propertyLocation.region
-- record.propertyLocation.canton
-- record.propertyLocation.cantonCode
-- record.propertyLocation.country
-- record.propertyLocation.countryCode
-- record.propertyLocation.city
-- record.propertyLocation.street
-- record.propertyLocation.zip

CREATE TABLE IF NOT EXISTS `tamedia_listings` (
  `type` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.adId` INT NULL,
  -- `record.url` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.ownObjectUrl` JSON NULL,
  -- `record.title` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.crawlerSource` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.availableFrom` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.availableUntil` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.modifiedDate` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.saleType` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.source` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.language` VARCHAR(3) CHARACTER SET utf8 NULL,
  -- `record.country` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.imageLinks` JSON NULL,
  -- `record.images` JSON NULL,
  `record.originalPropertyCategory` VARCHAR(64) CHARACTER SET utf8 NULL,
  `record.propertyCategory` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.propertyCategoryId` INT NULL,
  -- `record.breadcrumbs` JSON NULL,
  -- `record.crawlDatetime` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.floor` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.floorsInHouse` VARCHAR(64) CHARACTER SET utf8 NULL,
  -- `record.description` TEXT CHARACTER SET utf8 NULL,
  -- `record.grossPrice` FLOAT NULL,
  -- `record.visitsInfo` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.sellerType` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.crawlType` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.id` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.name` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.info` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.image` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.region` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.canton` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.cantonCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.country` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.countryCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.city` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.street` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.zip` INT NULL,
  -- `record.seller.location.coordinates.lat` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.location.coordinates.lon` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.seller.contact.phoneNumber` JSON NULL,
  -- `record.seller.contact.email` JSON NULL,
  -- `record.seller.contact.website` JSON NULL,
  -- `record.seller.contact.socialMedia` JSON NULL,
  -- `record.company.id` INT NULL,
  -- `record.company.name` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.page` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.logo` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.info` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.id` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.name` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.image` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.region` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.canton` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.cantonCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.country` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.countryCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.city` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.street` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.zip` INT NULL,
  -- `record.company.agent.location.coordinates.lat` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.location.coordinates.lon` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.agent.contact.phoneNumber` JSON NULL,
  -- `record.company.agent.contact.email` JSON NULL,
  -- `record.company.agent.contact.website` JSON NULL,
  -- `record.company.agent.contact.socialMedia` JSON NULL,
  -- `record.company.location.region` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.canton` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.cantonCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.country` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.countryCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.city` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.street` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.zip` INT NULL,
  -- `record.company.location.coordinates.lat` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.location.coordinates.lon` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.company.contact.phoneNumber` JSON NULL,
  -- `record.company.contact.email` JSON NULL,
  -- `record.company.contact.website` JSON NULL,
  -- `record.company.contact.socialMedia` JSON NULL,
  -- `record.newProperty` BOOL NULL,
  `record.price` FLOAT NULL,
  -- `record.oldPrice` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.netPrice` FLOAT NULL,
  -- `record.plotArea` INT NULL,
  -- `record.currency` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.buildYear` INT NULL,
  -- `record.propertyReference` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.publishedDate` timestamp NULL,
  -- `record.paymentInterval` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.livingSpace` INT NULL,
  -- `record.additionalCosts` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.rooms` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.bathrooms` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.deposit` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.parking` BOOL NULL,
  -- `record.garage` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.parkingPrice` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.reviews` JSON NULL,
  -- `record.comments` JSON NULL,
  -- `record.firstSeen` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.region` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.canton` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.cantonCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.country` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.countryCode` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.city` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.street` VARCHAR(256) CHARACTER SET utf8 NULL,
  `record.propertyLocation.zip` INT NULL
  -- `record.propertyLocation.coordinates.lat` FLOAT NULL,
  -- `record.propertyLocation.coordinates.lon` FLOAT NULL,
  -- `record.characteristics.propParking` BOOL NULL,
  -- `record.saleTypeId` INT NULL,
  -- `record.isHighlighted` BOOL NULL,
  -- `record.isTop` BOOL NULL,
  -- `record.t2t` VARCHAR(256) CHARACTER SET utf8 NULL,
  -- `record.hgPropertyCategory` JSON NULL
);

-- auto-generated definition
create table tamedia_listings
(
    type                                  varchar(64)   null,
    `record.saleType`                     varchar(256)  null,
    `record.source`                       varchar(256)  null,
    `record.language`                     varchar(3)    null,
    `record.originalPropertyCategory`     varchar(64)   null,
    `record.propertyCategory`             varchar(64)   null,
    `record.sellerType`                   varchar(256)  null,
    `record.price`                        float                     null,
    `record.netPrice`                     float                     null,
    `record.publishedDate`                int          default 0,
    `record.propertyLocation.region`      varchar(256)  null,
    `record.propertyLocation.canton`      varchar(256)  null,
    `record.propertyLocation.cantonCode`  varchar(256)  null,
    `record.propertyLocation.country`     varchar(256)  null,
    `record.propertyLocation.countryCode` varchar(256)  null,
    `record.propertyLocation.city`        varchar(256)  null,
    `record.propertyLocation.street`      varchar(256)  null,
    `record.propertyLocation.zip`         int                       null
) charset = utf8;

-- INSERT INTO `tamedia_listings` (`record.saleType`,`record.source`,`record.language`,`record.originalPropertyCategory`,`record.propertyCategory`,`record.sellerType`,`record.price`,`record.netPrice`,`record.propertyLocation.region`,`record.propertyLocation.canton`,`record.propertyLocation.cantonCode`,`record.propertyLocation.country`,`record.propertyLocation.countryCode`,`record.propertyLocation.city`,`record.propertyLocation.street`,`record.propertyLocation.zip`, `record.publishedDate`)
-- VALUES

